### ISSUE TITLE
Nuget package for PCL Profile 259 missing

### ISSUE THREAD

**Issue by ehuna** [kentcb/KBCsv#13]
Trying to get the nuget package for PCL Profile 259 and getting the error below.  How hard would it be to get a Nuget Package targetting PCL Profile 259?

Thanks!

PM> Install-Package KBCsv
Attempting to gather dependency information for package 'KBCsv.4.0.0' with respect to project 'MYCOMPANY.MYPROJECT.Core.ViewModels', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
Attempting to resolve dependencies for package 'KBCsv.4.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'KBCsv.4.0.0'
Resolved actions to install package 'KBCsv.4.0.0'
  GET https://api.nuget.org/packages/kbcsv.4.0.0.nupkg
  OK https://api.nuget.org/packages/kbcsv.4.0.0.nupkg 25ms
Installing KBCsv 4.0.0.
Install failed. Rolling back...
Package 'KBCsv.4.0.0' does not exist in project 'MYCOMPANY.MYPROJECT.Core.ViewModels'
Package 'KBCsv.4.0.0' does not exist in folder 'C:\code\MYPATH\MYCOMPANY\Dev\Src\packages'
Install-Package : Could not install package 'KBCsv 4.0.0'. You are trying to install this package into a project that targets 
'.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package KBCsv
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>

**Comment by ehuna** [comment]
I did pull the code and re-compiled for Profile259 and it works without problems.  I'll look into how to create multiple Nuget package and will issue a pull request at some point, if you don't beat me to it.  

Awesome work, thank you.

**Comment by kentcb** [comment]
@ehuna the latest KBCsv does away with portable profiles altogether and targets netstandard instead.
