### ISSUE TITLE
new CsvReader("data.csv")) ?

### ISSUE THREAD

**Issue by colgreen** [kentcb/KBCsv#14]
Hi. This simple example from your README.md doesn't appear to compile due to there being no constructor that takes a filename.

Am I missing something really obvious?

For now I'm just doing:

            using (var streamReader = new StreamReader("foo.csv"))
            using(CsvReader csvRdr = new CsvReader(streamReader)
            {
            }

Which is fine, but not sure if the README just needs updating, or if there was an intention to support thw overload, or if I'm just missing a namespace include/using for some extension class.

Thanks!

**Comment by kentcb** [comment]
Good catch @colgreen - sorry about that. KBCsv used to support that constructor overload. However, since moving to a PCL it is no longer possible and was removed. I'll update the readme tomorrow.

**Comment by kentcb** [comment]
Fixed!
