### ISSUE TITLE
Not able to import the text containing quotes in the some of the use cases 

### ISSUE THREAD

**Issue by NeelamKatwe** [kentcb/KBCsv#15]
I was trying to import the .csv file with a string containing quotes as shown in below examples.
To read the .csv I was using  KBCsv.dll (Version: 4.0.0.0)
The CsvReader consider the "" as ValueDelimeter and hence the imported strings discard the "" as shown in Example1
Example1 : My"Example"String 
Result of  Example1: MyExampleString 

So, we  decorated the part of string with """" to import "".
Example2 : My""Example""String
Result of  Example2: MyExampleString 

But when the string which contains dot(.) as shown in below example,  then the "" are not imported. 
Example3: S1.""opctags"".test8
Result of  Example3: S1.opctags.test8

Below is the entire .csv file text which we tried to import:
Action Type,Point Name,Tag Name,Item Path,Min Scale,Max Scale,Unit,Data Type
Add,,,S1.""opctags"".test8,0,100,mm/s/lbf,float

One way to import the string mentioned in Example3 is to overide the ValueDelimeter.
Is there any other way to import this kind of text?

**Comment by LightningMurakumo** [comment]
This is not a bug; your CSV file is malformed. 

When you set ValueDelimiter to double quotes ("), then any string containing double quotes _must be entirely enclosed by double quotes._

Make it look line this, and it will work fine:

Action Type,Point Name,Tag Name,Item Path,Min Scale,Max Scale,Unit,Data Type
Add,,,**"**S1.""opctags"".test8**"**,0,100,mm/s/lbf,float

**Comment by NeelamKatwe** [comment]
Thanks!!
It works fine with your suggested solution.

**Comment by kentcb** [comment]
Thanks @LightningMurakumo
