### ISSUE TITLE
Flush not called when leaveOpen: true

### ISSUE THREAD

**Issue by Reonekot** [kentcb/KBCsv#18]
I don't know if this is by design, (the documentation didn't call it out at least) but it did surprise me a bit as it didn't show in my first tests.

When creating CsvWriter with leaveOpen true, Dispose() doesn't call flush on the below stream. So the following code doesn't work correctly:

    var stream = new MemoryStream();

    using (var writer = new CsvWriter(stream, Encoding.UTF8, leaveOpen: true))
    {
        await writer.WriteRecordsAsync(records, 0, records.Length);
    }

Maybe Dispose() could be something like:

    if (!disposing)
        return;

    if (this.leaveOpen)
        this.textWriter.Flush();
    else
        this.textWriter.Dispose();

https://github.com/kentcb/KBCsv/blob/1e08a54c9137ecd00f078fa8597108e5d56e4ce1/Src/KBCsv/CsvWriter.cs#L426

**Comment by kentcb** [comment]
A quick test of the BCL's behavior (which is also hard to ascertain from comments) shows that you're right:

```csharp
var ms = new MemoryStream();
var sw = new StreamWriter(ms, Encoding.UTF8, 1024, true);

sw.WriteLine("Hello");
sw.Dispose();

// If sw is disposed, this outputs 10 bytes. If sw is not disposed, this outputs nothing.
ms.ToArray().Dump();
```

I'll get this fixed for the next release. Thanks for reporting (and sorry for taking so long to get to this. Life).

**Comment by kentcb** [comment]
Fixed in the upcoming release.
