### ISSUE TITLE
CsvReader(string???)

### ISSUE THREAD

**Issue by chadbruels** [kentcb/KBCsv#20]
Kent, I am maintaining a project and found it used Kent.Boogaart.KBCsv. Of course the reference was broken as the assembly was not included in source control. I found your project here, downloaded, and compiled. I have a problem with an instantiation of CsvReader(). The code I'm maintaining passes a string as a filename. You're project I've found only has Stream or TextReader. Did you at one time have a version with a string parameter as an overload? 

https://www.screencast.com/t/cKRdp8Oc

**Comment by kentcb** [comment]
Hi Chad,

Couple of things to be aware of:

1. KBCsv v4 simplified naming and NuGet packages. Everything changed from `Kent.Boogaart.KBCsv` to just `KBCsv`. NuGet package [here](https://www.nuget.org/packages/KBCsv/).
2. KBCsv v5 moved to netstandard, which does not support creating streams.

Seems like you're depending on an older version of KBCsv the delisted Kent.Boogaart.KBCsv NuGet package.

I'd advise updating to KBCsv v4 at a minimum, possibly even v5 if you're ready to move to netstandard.
