### ISSUE TITLE
Change names to shorter

### ISSUE THREAD

**Issue by asd-and-Rizzo** [kentcb/KBCsv#4]
Right now have
```
Kent.Boogaart.KBCsv
Kent.Boogaart.KBCsv.Extensions
```

1. Try out .NET BCL approach when Extension extend root namespace and do not have their own. Drop Extensions namespace, only in dll name. Put DataTable extensions into its namespace.

2. Kent.Boogaart.KBCsv has KB 2 times. Drop KB. Get like Kent.Boogaart.Csv

3. You have long name hard to remember. With 2 o and 2 a. Rename to kentcb and get

```
Kentcb.Csv
```

Value: ease of discovery and typing. You may try renaming when creating backward incompatible changes.

**Comment by kentcb** [comment]
Considering type forwarding as a solution to this problem. My intention would be to change the namespace to `KBCsv`. However, NuGet packages may be more difficult to update without disruption.

**Comment by kentcb** [comment]
The next version of KBCsv (4.0.0) has removed "Kent.Boogaart." from all packages and namespaces.

Unfortunately, type forwarding was not an option. Instead, I need to break clients. I will be releasing the new NuGets first, then an update to the old packages that intentionally breaks consumers. It will include a readme with instructions on upgrading.

Once upgraded, it's a simple search/replace to switch namespaces.
