### ISSUE TITLE
Add DataTable.WriteCsv with delimeter support

### ISSUE THREAD

**Issue by asd-and-Rizzo** [kentcb/KBCsv#5]
I do next
```fsharp
    let csv = new CsvWriter(target)
    dataTable.WriteCsv(csv,true) |> ignore
```
But cannot find how to specify delimiter or ensure that it is TAB.

**Comment by kentcb** [comment]
I don't know F# well, but you just need to set the `ValueDelimiter` property on the `CsvWriter`.
