### ISSUE TITLE
Create .NET 4.0 Nuget package

### ISSUE THREAD

**Issue by asd-and-Rizzo** [kentcb/KBCsv#7]
I nuget this lib with extensions into .NET 4.0 desktop project in F#. And got total hell with dependencies. Could not build or run.
May you create specific package for old development model when all dlls are references against full .NET not downloads.

My case is : 

1. F# dll project for .NET 4.0 target nugets KBCsv.Extensions
2. C# project for .NET 4.0  refrences F# project.

I cannot build them together.

**Comment by kentcb** [comment]
Please use an older version if you want (v2.0.2 might be best).
