### ISSUE TITLE
Add ability to ignore some properties

### ISSUE THREAD

**Issue by pogione** [kentcb/KBCsv#9]
Basically how JsonIgnore works as described here
http://james.newtonking.com/archive/2009/10/23/efficient-json-with-json-net-reducing-serialized-json-size

public class Car
{
  // included in JSON
  public string Model { get; set; }
  public DateTime Year { get; set; }
  public List<string> Features { get; set; }
 
  // ignored
  [JsonIgnore]
  public DateTime LastModified { get; set; }
}

Would be handy for .WriteCsv(writer);

**Comment by kentcb** [comment]
Done (in v4.0.0). Can now mark properties with `CsvIgnore` and the reflection-based overloads of `WriteCsv` will ignore them.
